import { Car } from './types/interface';

const carList: Car[] = [
    {
        id: '1',
        popular: true,
        brand: 'BMW',
        image: 'bmw3.jpg',
        model: '3',
        body: 'sedan',
        fuelType: 'petrol',
        engineSize: '2.0',
        price: '34.990',
    },
    {
        id: '2',
        popular: false,
        brand: 'BMW',
        image: 'bmw5.jpg',
        model: '5',
        body: 'sedan',
        fuelType: 'petrol',
        engineSize: '2.5',
        price: '49.990',
    },
    {
        id: '3',
        popular: false,
        brand: 'BMW',
        image: 'bmwX1.jpg',
        model: 'X1',
        body: 'SUV',
        fuelType: 'petrol',
        engineSize: '2.0',
        price: '35.690',
    },
    {
        id: '4',
        popular: false,
        brand: 'BMW',
        image: 'bmwX3.jpg',
        model: 'X3',
        body: 'SUV',
        fuelType: 'diesel',
        engineSize: '3.0',
        price: '46.390',
    },
    {
        id: '5',
        popular: true,
        brand: 'BMW',
        image: 'bmwX5.jpg',
        model: 'X5',
        body: 'SUV',
        fuelType: 'diesel',
        engineSize: '4.0',
        price: '73.490',
    },
    {
        id: '6',
        popular: true,
        brand: 'Volkswagen',
        image: 'VWGolf.jpg',
        model: 'Golf',
        body: 'hatchback',
        fuelType: 'petrol',
        engineSize: '1.4',
        price: '27.290',
    },
    {
        id: '7',
        popular: false,
        brand: 'Volkswagen',
        image: 'VWPolo.jpg',
        model: 'Polo',
        body: 'sedan',
        fuelType: 'petrol',
        engineSize: '1.6',
        price: '18.690',
    },
    {
        id: '8',
        popular: true,
        brand: 'Volkswagen',
        image: 'VWPassat.jpg',
        model: 'Passat',
        body: 'sedan',
        fuelType: 'petrol',
        engineSize: '2.0',
        price: '26.690',
    },
    {
        id: '9',
        popular: true,
        brand: 'Renault',
        image: 'renaultLogan.jpg',
        model: 'Logan',
        body: 'sedan',
        fuelType: 'petrol',
        engineSize: '1.6',
        price: '14.390',
    },
    {
        id: '10',
        popular: false,
        brand: 'Renault',
        image: 'renaultStepway.jpg',
        model: 'Stepway',
        body: 'hatchback',
        fuelType: 'petrol',
        engineSize: '1.6',
        price: '15.890',
    },
    {
        id: '11',
        popular: true,
        brand: 'Renault',
        image: 'renaultDuster.jpg',
        model: 'Duster',
        body: 'SUV',
        fuelType: 'diesel',
        engineSize: '1.5',
        price: '19.790',
    },
    {
        id: '12',
        popular: false,
        brand: 'Renault',
        image: 'renaultKaptur.jpg',
        model: 'Kaptur',
        body: 'SUV',
        fuelType: 'petrol',
        engineSize: '1.6',
        price: '23.190',
    },
    {
        id: '13',
        popular: false,
        brand: 'Renault',
        image: 'renaultArkana.jpg',
        model: 'Arkana',
        body: 'SUV',
        fuelType: 'petrol',
        engineSize: '1.9',
        price: '29.890',
    },
    {
        id: '14',
        popular: false,
        brand: 'Toyota',
        image: 'toyotaCorolla.jpg',
        model: 'Corolla',
        body: 'sedan',
        fuelType: 'petrol',
        engineSize: '1.6',
        price: '25.890',
    },
    {
        id: '15',
        popular: true,
        brand: 'Toyota',
        image: 'toyotaCamry.jpg',
        model: 'Camry',
        body: 'sedan',
        fuelType: 'petrol',
        engineSize: '2.5',
        price: '33.290',
    },
    {
        id: '16',
        popular: false,
        brand: 'Toyota',
        image: 'toyotaC-HR.jpg',
        model: 'C-HR',
        body: 'SUV',
        fuelType: 'petrol',
        engineSize: '2.0',
        price: '34.590',
    },
    {
        id: '17',
        popular: true,
        brand: 'Toyota',
        image: 'toyotaRAV4.jpg',
        model: 'RAV4',
        body: 'SUV',
        fuelType: 'petrol',
        engineSize: '2.0',
        price: '42.190',
    },
    {
        id: '18',
        popular: true,
        brand: 'Toyota',
        image: 'toyotaPrado.jpg',
        model: 'Land Cruiser Prado',
        body: 'SUV',
        fuelType: 'petrol',
        engineSize: '2.7',
        price: '58.190',
    },
    {
        id: '19',
        popular: true,
        brand: 'Hyundai',
        image: 'hyundaiAccent.jpg',
        model: 'Accent',
        body: 'sedan',
        fuelType: 'petrol',
        engineSize: '1.4',
        price: '15.890',
    },
    {
        id: '20',
        popular: false,
        brand: 'Hyundai',
        image: 'hyundaiSonata.jpg',
        model: 'Sonata',
        body: 'sedan',
        fuelType: 'petrol',
        engineSize: '2.0',
        price: '34.490',
    },
    {
        id: '21',
        popular: true,
        brand: 'Hyundai',
        image: 'hyundaiCreta.jpg',
        model: 'Creta',
        body: 'SUV',
        fuelType: 'petrol',
        engineSize: '1.6',
        price: '21.990',
    },
    {
        id: '22',
        popular: false,
        brand: 'Hyundai',
        image: 'hyundaiTucson.jpg',
        model: 'Tucson',
        body: 'SUV',
        fuelType: 'petrol',
        engineSize: '2.0',
        price: '36.590',
    },
    {
        id: '23',
        popular: true,
        brand: 'Hyundai',
        image: 'hyundaiSantafe.jpg',
        model: 'Santa Fe',
        body: 'SUV',
        fuelType: 'diesel',
        engineSize: '2.2',
        price: '43.190',
    },
];

export default carList;
