export default [
    {
        brand: 'BMW',
        image: 'bmw3.jpg',
        model: '3',
        body: 'sedan',
        fuelType: 'petrol',
        engineSize: '2.0',
        price: '34.990',
    },
    {
        brand: 'BMW',
        image: 'bmw5.jpg',
        model: '5',
        body: 'sedan',
        fuelType: 'petrol',
        engineSize: '2.5',
        price: '49.990',
    },
    {
        brand: 'BMW',
        image: 'bmwX1.jpg',
        model: 'X1',
        body: 'SUV',
        fuelType: 'petrol',
        engineSize: '2.0',
        price: '35.690',
    },
    {
        brand: 'BMW',
        image: 'bmwX3.jpg',
        model: 'X3',
        body: 'SUV',
        fuelType: 'diesel',
        engineSize: '3.0',
        price: '46.390',
    },
    {
        brand: 'BMW',
        image: 'bmwX5.jpg',
        model: 'X5',
        body: 'SUV',
        fuelType: 'diesel',
        engineSize: '4.0',
        price: '73.49',
    },
    {
        brand: 'Volkswagen',
        image: 'VWGolf.jpg',
        model: 'Golf',
        body: 'hatchback',
        fuelType: 'petrol',
        engineSize: '1.4',
        price: '27.290',
    },
    {
        brand: 'Volkswagen',
        image: 'VWPolo.jpg',
        model: 'Polo',
        body: 'sedan',
        fuelType: 'petrol',
        engineSize: '1.6',
        price: '18.690',
    },
    {
        brand: 'Volkswagen',
        image: 'VWPassat.jpg',
        model: 'Passat',
        body: 'sedan',
        fuelType: 'petrol',
        engineSize: '2.0',
        price: '26.690',
    },
    {
        brand: 'Renault',
        image: 'renaultLogan.jpg',
        model: 'Logan',
        body: 'sedan',
        fuelType: 'petrol',
        engineSize: '1.6',
        price: '14.390',
    },
    {
        brand: 'Renault',
        image: 'renaultStepway.jpg',
        model: 'Stepway',
        body: 'hatchback',
        fuelType: 'petrol',
        engineSize: '1.6',
        price: '15.890',
    },
    {
        brand: 'Renault',
        image: 'renaultDuster.jpg',
        model: 'Duster',
        body: 'SUV',
        fuelType: 'diesel',
        engineSize: '1.5',
        price: '19.790',
    },
    {
        brand: 'Renault',
        image: 'renaultKaptur.jpg',
        model: 'Kaptur',
        body: 'SUV',
        fuelType: 'petrol',
        engineSize: '1.6',
        price: '23.190',
    },
    {
        brand: 'Renault',
        image: 'renaultArkana.jpg',
        model: 'Arkana',
        body: 'SUV',
        fuelType: 'petrol',
        engineSize: '1.9',
        price: '29.890',
    },
    {
        brand: 'Toyota',
        image: 'toyotaCorolla.jpg',
        model: 'Corolla',
        body: 'sedan',
        fuelType: 'petrol',
        engineSize: '1.6',
        price: '25.890',
    },
    {
        brand: 'Toyota',
        image: 'toyotaCamry.jpg',
        model: 'Camry',
        body: 'sedan',
        fuelType: 'petrol',
        engineSize: '2.5',
        price: '33.290',
    },
    {
        brand: 'Toyota',
        image: 'toyotaC-HR.jpg',
        model: 'C-HR',
        body: 'SUV',
        fuelType: 'petrol',
        engineSize: '2.0',
        price: '34.590',
    },
    {
        brand: 'Toyota',
        image: 'toyotaRAV4.jpg',
        model: 'RAV4',
        body: 'SUV',
        fuelType: 'petrol',
        engineSize: '2.0',
        price: '42.190',
    },
    {
        brand: 'Toyota',
        image: 'toyotaPrado.jpg',
        model: 'Land Cruiser Prado',
        body: 'SUV',
        fuelType: 'petrol',
        engineSize: '2.7',
        price: '58.190',
    },
    {
        brand: 'Hyundai',
        image: 'hyundaiAccent.jpg',
        model: 'Accent',
        body: 'sedan',
        fuelType: 'petrol',
        engineSize: '1.4',
        price: '15.890',
    },
    {
        brand: 'Hyundai',
        image: 'hyundaiSonata.jpg',
        model: 'Sonata',
        body: 'sedan',
        fuelType: 'petrol',
        engineSize: '2.0',
        price: '34.490',
    },
    {
        brand: 'Hyundai',
        image: 'hyundaiCreta.jpg',
        model: 'Creta',
        body: 'SUV',
        fuelType: 'petrol',
        engineSize: '1.6',
        price: '21.990',
    },
    {
        brand: 'Hyundai',
        image: 'hyundaiTucson.jpg',
        model: 'Tucson',
        body: 'SUV',
        fuelType: 'petrol',
        engineSize: '2.0',
        price: '36.590',
    },
    {
        brand: 'Hyundai',
        image: 'hyundaiSantafe.jpg',
        model: 'Santa Fe',
        body: 'SUV',
        fuelType: 'diesel',
        engineSize: '2.2',
        price: '43.190',
    },
];
